### ISSUE TITLE
version 24 and 25

### ISSUE THREAD

**Issue by yoobi** [inovex/gitlab-ci-android#23]
Hello,

I'm using your docker image on gitlab and it has been working properly but I'm getting issue with the last two versions (24 and 25).

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

My .gitlab-ci.yml looks like
```yml
image: inovex/gitlab-ci-android:23

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

.only-main:
  only:
    - main

stages:
  - publish

publish:
  extends: .only-main
  stage: publish
  script:
    - java -version
    - ./gradlew :my-awesome-library:publish

```
